deliveroo/deliveroo.engineering

_guidelines/api-design.md

In parallel with #16 where we start do document how we build services, it's probably a good time to start discussing our API design conventions.
I'd stress that the point here is to have something normative for _internal_ (inter-service) APIs, but some of these constraints may need relaxing somewhat for outwards-facing APIs (public APIs, mobile APIs) which have particular performance and security constraints.

HTTP API Guidelines

---

_data/routes.yml

See: https://www.sitepoint.com/hacking-routing-component-jekyll/
We’re writing templates in HTML/Liquid rather than Markdown, but it should still make it easier to keep routes up to date than manually typing them in places.

Add a basic routing tool rather than hard-coding URLs

---

articles/index.html

This is a placeholder index page for the `/articles/` page.

Add basic articles placeholder index

---

_guidelines/javascript.md
_guidelines/react.md

The syntax highlighter github-pages uses to generate nicely-formatted code examples offline is `rouge`, rather than the _Github-Flavored Markdown_ we’re familiar with seeing in issues and the markdown previews on github itself. Unfortunately Rouge doesn’t recognise code blocks with language identifiers (e.g. ````javascript`) if they’ve been indented by a tab or four spaces. Similarly, any _non-code_ blocks indented in this way are assumed to be code, even if they’re not. This results in this kind of output:
Fixing the indentation gives us the desired results:

Fix indentation preventing Rouge syntax highlighting

---

_guidelines/javascript.md

This reformats the JavaScript guidelines page (one of the most well-developed of our guidelines pages) to work better with:
* Kramdown’s Markdown renderer
* the new blog layout
* metadata needed for layouts other than this article page
Things of note:
* We can automatically generate a table of contents with Kramdown’s `{:toc}` identifier; this hooks into headings, and so will automatically use those headings. For this reason I’ve changed various subsections into subheadings (h3s). The list item with text `Automatic Table of Contents Here` is automatically replaced with this table of contents.
* Changed references to external linter guides to use footnotes (`[^footnote]`) which are then automatically generated at the bottom of the document.
* Reformatted some of the `> Why?` text to make …

Reformat JavaScript guidelines page

---

_guidelines/00-meta.md
_guidelines/active-record.md
_guidelines/api-design.md
_guidelines/git.md
_guidelines/java-android.md
_guidelines/java.md
_guidelines/objective-c.md
_guidelines/react.md
_guidelines/rspec.md
_guidelines/ruby.md
_guidelines/services.md

These changes update the layout/formatting of the various guideline documents to bring them in line with what the new blog layout expects, including:
* Adding Front Matter descriptions/titles
* Correcting heading levels
* Adding Table of Contents identifiers
* Made code blocks consistently use the ``` block identifier instead of indentation
* General tidying up
I’ve also added some more detail about Markdown guidelines to the meta document which describes the kind of thing I’ve added with this PR, so that future guidelines can make use of them.

Update format of guidelines & add descriptions

---

_guidelines/git.md

Tweaked the formatting here a bit:
* Split out subheadings so that they’re part of the table of contents.
* Use _emphasis_ rather than **strong emphasis** in most places

Update formatting for git guidelines

---

_sass/local/_layout.scss

This PR fixes a couple of sets of flexbox bugs:
* Safari 9 wasn’t correctly displaying flex columns
* The sticky footer wasn’t being sticky when there wasn’t enough content to fill the viewport

Fix flexbox layout issues

---

_posts/2016-09-19-ab-testing-cdns.md

Post date is inferred from the post filename, so this field is unnecessary.

Remove superfluous date front matter from posts

---

_guidelines/api-design.md

After chats with @gbonfant, @rfonglip, and @gregbeech, this corrects our example collection responses to:
- properly include links to the resources in the collection
- fix the links themselves (they were missing the `href` nesting)
- make it more obvious embedding should not be the norm

API guidelines: fix for collections

---

_guidelines/javascript.md

The JS guidelines doc has a bunch of footnotes, but no subheading indicating them as such, so they run into the preceding references subsection; adding a subheading (without content below) addresses this.

Add footnotes subheading to JS guidelines doc

---

_sass/local/content.scss

This change makes the specific footnote you’ve been taken to from within the body more obvious, a la Wikipedia.

Highlight footnotes when linked to from article body

---

_config.yml
articles/index.html

Hi,
this adds a simple pagination to the `/articles` page as it was mentioned in #58 via `jekyll-paginate` which is already installed on github pages.

add pagination to articles page

---

_sass/base/_default.scss
_sass/layout/content.scss

Compared to both Stratos and Adelle Sans, monospace fonts seem a little large; this PR improves (and is more explicit about) font sizes for these whenever `<code>` occurs inline within headings or the table of contents.
Example:

Improve font sizes of code within headings/TOC

---

_guidelines/react.md
_guidelines/redis.md

* Use footnote syntax where appropriate
* Reformat a few code examples
* Fix a few typos
* ~Use smart quotes~ not needed since Kramdown does this for us

Update formatting in a few recent guideline updates

---

_data/routes.yml

Tiny PR to update the food blog URL in the footer.

Update food blog URL in footer

---

_guidelines/00-meta.md

The README mentions branch-naming, but the meta-guidelines didn’t (yet), so this addresses that (and also refines the review steps, since we don’t permit in-situ editing).

Update meta-guidelines to mention branch naming

---

_guidelines/javascript.md

Fix broken markdown footnote syntax with the caret outside the brackets (oops).

Fix typo with footnote syntax.

---

_guidelines/ruby.md

This PR adds a simple preamble to the Ruby style guide based around the one used in @bbatsov’s [guide](https://github.com/deliveroo/deliveroo.engineering/blob/master/ruby.md) which is being used as a basis for our own Ruby style guide.

Add preamble to Ruby style guide

---

_sass/layout/content.scss

After feedback from @phuly I’ve made some minor tweaks to improve the typography across the engineering site:
* Increased line height to 1.8
* Decreased the maximum container width for the homepage (reducing the maximum line length as a result):

Improve typography layout

---

_guidelines/active-record.md

This adds a few notes on database column naming: no abbreviations, common suffixes, and the `cached_` prefix.

Adds notes on column naming

---

_guidelines/ruby.md

Initial set of Ruby formatting guidelines based on @bbatsov’s [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide).
I’ve reformatted the guidelines to work within the Engineering Blog template, plus I’ve shuffled a few things around to group them a bit more logically (so that we can have subheadings, to more easily have shareable links to a given subject).

Ruby formatting guidelines

---

_includes/byline.html
_layouts/post.html
_sass/layout/content.scss

**Desktop small and up:**
**Tablet/mobile:**

Feature: Link author name across site and add About Author section on posts

---

_posts/2017-01-19-optimising-membership-queries.md

This fixes display of the excerpt on Julien's blog post. 
As this branch was created before the code-wide spelling fix for excerpt, Julien's post is not correctly displaying his intended excerpt text and instead duplicating the first para of the post's body text.

Fix excerpt display on Julien’s post

---

README.md

I encountered problems running `bundle install` on a fresh macOS Sierra machine, specifically with getting nokogiri to build. The workaround instructions are contained within this PR.

Add workaround instructions for nokogiri

---

.gitignore
Gemfile
Gemfile.lock
_includes/head.html
_layouts/default.html
_layouts/post.html

This PR adds opengraph metadata to the site, both for generic pages and with additional metadata for article pages:
_(N.B. the `localhost:4000` examples you see here come from `site.url`, so this will be correct in production)_

Add opengraph metadata

---

_guidelines/01-naming-things.md

According to recommendation the name should be `roo-it-production`.
It also contains some automatic removal of whitespace at the end of the lines. 
Please give some feedback on what is the general approach for this (whitespace removal and code formatting in general).

Fix example for naming app

---

_guidelines/active-record.md

Small fix : The Query Object method used in examples is `#call` while the documentation just above that used `#execute`.
Also a small typo and automatic end-of-line whitespace removal.

Guidelines/active-record Fix query object documented method name

---

Gemfile.lock
_config.yml
_includes/head.html

This adds the [jekyll-seo-tag](https://github.com/jekyll/jekyll-seo-tag) plugin, which is available with `github-pages`. I removed the tags we set manually and are now set by the plugin.
~~- [ ] add twitter username per author for twitter cards~~

add `jekyll-seo-tag`

---

_sass/layout/content.scss
articles/index.html

Just a little PR to improve how the pagination controls appear.
Before:
After:

Improve the layout of the pagination controls

---

_guidelines/api-design.md

>a the
That caught my eye.
I decided to remove the "the". While I was at it, I removed "mandatory" because it's redundant (it follows "_must_ include").
---
Update: also spotted another typo in that sentence and fixed it; "_may_ embedded" -> "_may_ embed"

API Design: typo

---

javascript/careers.js

This changes the filter setting for the workable JS on the careers page to pull in listings under `Engineering` rather than `Product Team` (which recruitment no longer uses).

Change filter on Careers page to refer to Engineering group on Workable

---

_guidelines/00-meta.md

Before:
After:
It looks like the markdown parser doesn't like the nested code blocks, this commit replaces the outer block with an indent instead.

Fix trailing ``` in guidelines/meta

---

_guidelines/react.md
_sass/layout/content.scss
_sass/vendor/_monokai.scss

Somehow I recently introduced a layout bug with code blocks (this is why I hate `.single-class` selector rules). This PR fixes it:
**Before**
**After**

Fix issue with code block formatting

---

_guidelines/react.md

The version of `rouge` that `gh-pages` uses now finally supports JSX syntax highlighting, so we no longer have to fake it with `javascript` (and weird formatting) for those guidelines that have examples of JSX 🎉

Use JSX syntax highlighting for React guidelines

---

_sass/layout/content.scss

Minor tweak which improves how the list of other articles displays, to make it more space-efficient.
Above 640px wide:
Above 800px wide:

Use CSS grid to display the list of other articles

---

Gemfile.lock
_includes/analytics.html
_includes/cookie_consent.html
_includes/head.html

Currently we have no insight into the amount of visitors the Engineering blog has, or how many times specific articles are read. With this PR we will add Google Analytics to the Engineering blog to give us those insights.
Additionally, a cookie consent banner has been added to inform people of the use of cookies on the blog. I've used the same copy and explainer link for the cookie consent banner as on deliveroo.co.uk.
How the cookie consent banner works:

EB-18 Add Google Analytics

---

_config.yml
_includes/head.html

This commit updates the jekyll config to use the new og image.
The og image was missing before. I think updating the jekll made it start paying attention to that part of the config.

Update og image

---

_posts/2019-02-22-go-down-the-rabbit-hole.md

A post about debugging a proxy in go, some interesting characteristics
about how the go standard library treats requests and how our CDN acting
as a man in the middle 'fixes' some otherwise malformed requests.

post: Go down the rabbit hole

---

_posts/2019-02-22-go-down-the-rabbit-hole.md

Formatting fix: go_down_the_rabbit_hole
Previously the nginx buffers docs snippet was shown on one line. This
commit adds line breaks to make it easier to read.

Formatting fix: go_down_the_rabbit_hole

---

_config.yml

The "Work with us!" link is currently using the wrong team ID from the list (`engineering` instead of `engineering-team`)

Fix careers link

---

_config.yml
_data/offsets.yml
index.html

Currently on https://deliveroo.engineering we show 21 articles on the homepage, and if you click More Articles, the pagination shows articles 1-3 and you need to click through many pages to get to any articles that were not shown on the homepage.
- Calculates what the "next page" should be given the articles on the homepage. It should always take you to the page with the first article not shown on the homepage.
- How many articles are shown in each section on the homepage is now configurable in a yml file
- Increases pagination to 9; we now have enough articles to not restrict the number of articles per page so much; less clicky-clicky to get all the way through the backlog of articles.

Configures "More articles" to go to the right page

---

LICENSE.md

As per the website's footer, we're licensing content as CC-BY-SA-4.0 -
unless explicitly mentioned otherwise - so we should add a `LICENSE.md`
to make it more discoverable, as noted in #257.
Closes #257.

Add explicit LICENSE.md

---

_sass/abstract/_typography.scss
_sass/base/_default.scss

As it doesn't make sense, and poorly renders compared to being the
monospace fonts that are intended i.e. for code snippets.

fix(styles): don't use sans-serif font for monospace fonts
