_config.yml
_guidelines/00-meta.md
_layouts/guidelines.html

One guideline to guide them all.
This is the guideline on how to contribute to guidelines.
Review it, and give it a 👍 or a 👎 !

Guidelines on guidelines!

---

_guidelines/active-record.md

First part of our AR guidelines, ported from the "old" ones. Have a read, comment, give the PR a 👍 or 👎 !

Ruby / ActiveRecord guidelines, part 1

---

_guidelines/javascript.md

First addition to our code styles.
A lot of copy pasta from airbnb but I don't think there is too much contention over this point. Easy one to get the ball rolling!

Added js comma code style

---

_guidelines/react.md

Good practice for props on elements and components in react.
One I see quite a lot in pull requests is the last point.

Added a prop spec to the react props md

---

_guidelines/services.md
_sass/local/_components.scss
bin/serve

As there's increasing appetite to build services separate from the monolith, it's time to start discussing a shared approach.
As before, we're taking existing guidelines piecemeal and adapting them.
Comment away!

Building Services guidelines, part 1

---

_guidelines/javascript.md

Destructuring is kick-ass. We should use it whenever it makes sense which is all the time.

Added initial destructuring docs

---

_guidelines/api-design.md

This smaller change is an intro to how use domain modeling to design APIs.

API Guidelines: domain modeling

---

_guidelines/javascript.md

Inline with AirBnB eslint, the most popular standard currently in use.

Initial proposal for js naming conventions

---

.gitignore

Ignore OS X .DS_Store files

---

_config.yml
_data/routes.yml
guidelines/index.html

Add an index page for engineering guidelines.

Add guidelines page

---

_config.yml

* Update some of the blog metadata
* Enable parsing markdown within block level elements in markdown content files

Update blog settings

---

_guidelines/api-design.md

This covers paths, request/response headers, error handling, and importantly payload formatting.
Comment away!

API guidelines: request/response format

---

_guidelines/api-design.md
archive/apis.md

Previously we were suggesting using `no-store` which is almost never
what you want. This improves the suggestion for HTTP caching.

Improves the guidance on HTTP caching

---

_sass/local/content.scss

Change code blocks to be the same width as other guideline content

---

_sass/local/_layout.scss
_sass/local/content.scss
_sass/local/default.scss
_sass/local/footer.scss
_sass/local/header.scss
images/external_link_aubergine.svg
images/external_link_white.svg

Display an icon denoting external links

---

_sass/local/_monokai.scss
_sass/local/content.scss

* Adds some more SCSS-specific styles for the syntax highlighter
* Improve how inline code samples are displayed within articles
* Improve how the TOC list is displayed

Tighten up some style rules for articles

---

README.md
_guidelines/_example-guidelines.md
_posts/YYYY-MM-DD-your-blog-post-name.md

* Added a basic README with setup instructions and general information about adding guidelines / blog posts
* Added some sample guidelines / blog post files as templates
Fixes #60.

Add README

---

_config.yml
_data/routes.yml
_includes/head.html
_sass/abstract/_typography.scss
_sass/base/_default.scss
_sass/components/_forms.scss
_sass/layout/content.scss
_sass/layout/header.scss
_sass/pages/careers.scss
authors/index.html
careers/index.html
css/main.scss
index.html
javascript/careers.js

Add a careers page that pulls data in from Workable.

Deliveroo Engineer Careers page

---

_guidelines/redis.md

This just ports the Redis guide from https://github.com/deliveroo/roo_docs/blob/master/redis_models.md
When merging this, please also merge deliveroo/roo_docs#18 which deletes the original.

Redis guide

---

_guidelines/git.md

This addition covers naming branches, tagging commit messages, and titling PRs.

Git: Naming

---

_guidelines/seed-data.md

Adding a few guidelines for FactoryGirl definitions.

Examples and guidelines for FactoryGirl definitions

---

_guidelines/active-record.md
_guidelines/services.md

This updates/clarifies our guidelines after two recent incidents.
(no specifics on those here as this is a public repo)

Migrations + configuration update

---

_posts/2016-12-22-what-makes-a-good-tech-team-great.md

Forgot to add a paragraph on these very guidelines!

Added reference to guidelines

---

.gitignore
Gemfile
Gemfile.lock
_includes/head.html
_layouts/default.html
_layouts/post.html

Reverts deliveroo/deliveroo.engineering#118

Revert "Add opengraph metadata"

---

_guidelines/active-record.md

Making it more explicit on how to safely remove a column from a table.

Add guides for removing model columns

---

_guidelines/git.md

Adding this at @nronas's request. Not entirely sure it fits here but perhaps @gregbeech or @kapowaz will have an opinion?

Add a gem versioning section

---

_posts/2017-03-28-hackday-and-the-17pound-soda.md

checkout payment provider description

---

_posts/2016-09-19-ab-testing-cdns.md

Fixes some links in Julien's earliest article

Fixes links in Julien's article

---

_includes/footer.html

use dynamic year in footer

---

_guidelines/active-record.md

Raw SQL queries are bad. Storing posts in `@users` is worse. 😅

Fix snippets, links and typos in ActiveRecord guidelines

---

_posts/2017-11-23-engineering-interviews.md

I did not read the markdown docs correctly, the link currently 404s but this PR fixes that.

Fix link to distributed systems blog for interview post

---

_posts/2018-03-21-smooth-migrations.md

Added missing letter

---

Gemfile.lock
_includes/footer.html
_sass/layout/footer.scss

Add Twitter follow button to footer

---

README.md

As a new joiner (and a new blog post writer), it wasn't clear what the last stage of the review process, or `ready for editor review` label, involved.

Clarify feedback stage when submitting a blog post

---

_posts/2019-02-14-moving-from-ruby-to-rust.md

We are suggesting orders to the rider and not assigning them

Change the wording in moving from ruby to rust blog post

---

README.md
_config.yml
_posts/2016-12-22-what-makes-a-good-tech-team-great.md
_posts/2016-12-23-the-unbearable-rightness-of-being-wrong.md
_posts/2017-01-03-what-its-like-to-be-an-android-developer-at-deliveroo.md
_posts/2017-04-13-I-assess-quality-……-therefore-I-am.md

Fixed the Mixed Content failures that are happening on every PR

Fixed "Mixed Content" PR check failures

---

_posts/2021-11-10-engineering-culture-at-deliveroo.md
_posts/2021-11-11-why-culture-matters-in-your-data-science-team.md

- Engineering culture at Deliveroo
- Why culture matters in your data science team

Add two additional talk series posts

---

_posts/2023-01-24-roo-talks-care-august.md

As they ensure that the images are resized on smaller screens.

Wrap images in `<figure>`s

---

_posts/2023-01-24-roo-talks-care-august.md

- Add missing blurb about Care
- Remove smart quotes

Add missing blurb about Care

---

analytics.txt

As part of EB-29.
Validated with:
```
bundle exec jekyll build
cat _site/analytics.txt
```

Add Google Analytics ownership

---

README.md

- Remove guidelines contribution guide
- Add internal doc for contributing to the blog

Tweak "new blog post" contributing guide

---

_authors/jp-hastings-spital.md

Removes my twitter account link.

I'm no longer on Twitter
